# Generated by Django 4.2.4 on 2023-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('ano', models.DateField()),
                ('km', models.FloatField()),
                ('pagamento', models.CharField(max_length=100)),
                ('leilao', models.BooleanField()),
            ],
        ),
    ]
